### ISSUE TITLE
FYI: Your dependencies are out of date, npm install does not work for users

### ISSUE THREAD

**Issue by prodkt** [Dunqing/unocss-preset-theme#2]
npm i -D unocss-preset-theme
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @prodkt-cloud/bootstrap-static@0.0.1
npm ERR! Found: unocss@0.46.5
npm ERR! node_modules/unocss
npm ERR!   dev unocss@"^0.46.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer unocss@"^0.45.25" from unocss-preset-theme@0.1.1
npm ERR! node_modules/unocss-preset-theme
npm ERR!   dev unocss-preset-theme@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/prodkt/.npm/eresolve-report.txt for a full report.

**Comment by Dunqing** [comment]
Thank you for your feedback, this bug has been fixed in unocss-preset-theme@0.2.0. Please upgrade the version, Thanks!

**Comment by prodkt** [comment]
Thanks! Gave it a try with Astro and its not being seen to build out the variables in its state. I get no errors but the themes never produce. It was worth a shot, appreciate you updating the repo anyway.

**Comment by Dunqing** [comment]
> I get no errors but the themes never produce. It was worth a shot, appreciate you updating the repo anyway.

If the problem persists, please provide reproduction and I'll try to fix it.
