### ISSUE TITLE
Please if possible add a check for UnoCSS version when installing unocss-preset-theme

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [Dunqing/unocss-preset-theme#23]
I was very confused trying to get this to work, turns out it was because I'm using an older version of UnoCSS in order to avoid some bugs. That meant nothing happened because of (I'm guessing) https://github.com/Dunqing/unocss-preset-theme/commit/1bb8d25857ccc361162505ae41b6e2c67c8b6618

It would be nice if this preset could check for a compatible UnoCSS version to get the right package, no idea how to set that up though.

Anyway, thanks for a great theme!

**Comment by Dunqing** [comment]
Thanks for the feedback, I've set up peerDependencies so you’ll see a warning if the version you installed doesn't match.
https://github.com/Dunqing/unocss-preset-theme/blob/00a82c0f3972d6e8e0ee68f9ff5f7702fd15191d/package.json#L48
