### ISSUE TITLE
Support unocss@0.52

### ISSUE THREAD

**Issue by ModyQyW** [Dunqing/unocss-preset-theme#33]
Hi. Thanks for your great work!

I am developing `unocss-preset-element-plus` and `unocss-preset-antd` based on this preset. After I update to unocss 0.52, some type issues come out. Similar to https://github.com/Dunqing/unocss-preset-theme/issues/7.

<img width="1554" alt="image" src="https://github.com/Dunqing/unocss-preset-theme/assets/31850793/704f3c8c-8379-438c-90e2-4ad5f81d8003">

Some ideas: How about update package.json?

https://github.com/Dunqing/unocss-preset-theme/blob/82135e1031553ba6139576c79c3c615bb22d2cac/package.json#L47-L53

To

```json
{
	"peerDependencies": {
      "@unocss/core": ">=0.51"
    },
    "dependencies": {
      "@unocss/core": ">=0.51",
      "@unocss/preset-mini": ">=0.51"
    }
}
```

**Comment by Dunqing** [comment]
Now, The `unocss-preset-theme@0.7.0` have supported `unocss@0.52`

I have updated `peerDependencies` to use `>=`, but the `dependencies` I think it's good now.  Thank you for your advice！

**Comment by ModyQyW** [comment]
Thanks a lot!
