### ISSUE TITLE
Not working, theme values directly applied

### ISSUE THREAD

**Issue by silveltman** [Dunqing/unocss-preset-theme#41]
I have the following config:
```
// uno.config.ts
import { defineConfig, presetUno } from 'unocss'
import presetTheme from 'unocss-preset-theme'

export default defineConfig({
  theme: {
    colors: {
      mycolor: 'red'
    }
  },
  presets: [
    presetUno(),
    presetTheme({
      theme: {
        mytheme: {
          colors: {
            mycolor: 'blue'
          }
        },
      }
    })
  ],
})
```

it putputs this css:
```
/* layer: default */
.text-mycolor{color:blue;}
```

Am I missing something? 

Playground: https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCJ0D4BQwAWAjLIihgC4CmAHuQLQC2AnjAPZysBO2%2BlcHUAO5c4IYAHoiuCeAi48sksjTpm5Xg0rY8RJWXRVajFuy48%2BA4Z1ESpecbKA&config=PTAEFcDsHsDoGNqQGYEsDmsAuBnAUKgLYAO0ATlqAN6gAmApmpPQMJJroA0oxZ9O9LAFUYoAL6hkZaIVAByKNHg4ccgiXKVe-QQBUAFvUL1J02QpjKcAWm0Cs1rIeNq89AB6kKdRgENwADaUDEys7BgAFFR4oKBORvQAXNQxsaCIAeQ4ydFpaYQAnhnkyXJ8tGp5YqlinKl2gtmgANqpsQ3CMBEAlHV5HQYJUW1p8cY5I3mFY0kpefPp0JlkTbkL84XFZKUARgHg9JXrsdXHtZPiI2LdqQC6dddAA&css=Q&options=N4XyA

**Comment by Dunqing** [comment]
Your configuration of the default theme isn't right. The `fontSize` should define in `theme`, the same level as `colors`. 

You can see https://uno.antfu.me/play/?html=JAHgFgjABAxgNgQwM5ILwCIAuBTAHpgWgFsBPAMwHsA7TdAPjGzjgqgHcKAnOAExAHpIdAFChIsRCgw58xctUxREnAObZ6jZqw7c%2BgiHSA&config=PTAEFcDsHsDoGNqQGYEsDmsAuBnAUKgLYAO0ATlqAN6gAmApmpPQMJJroA0oxZ9O9LAFUYoAL6hkZaIVAByKNHg4ccgiXKVe-QQBUAFvUL1J02QpjKcAWm0Cs1rIeNq89AB6kKdRgENwADaUDEys7BgAFFR4oKBORvQAXNQxsZJIWADKqABeSSlpaYQAnsgZyXIALAAMxO5ynKmxYo2FiAHkOMlULam9sXaCXaAA2k08fPYi0BEAlK1pIAACuNYYMHzjg1gGCVHjsfHG3QeLYGwoGOB8dL5kANZxzvynsQF36PnRhT-pkFm5L6vH4lMr-CoANlq9QWv2asJ%2B-ThIFAFw41xMiBIvnglCOLzhoBwhF8AQCJ0JsTBALyFMpsVB5XkACZoQ1gfDgUjCtzxPNUgBdRpiWZ4IA&css=Q&options=N4XyA

**Comment by silveltman** [comment]
I see, stupid mistake.. Thanks!
