### ISSUE TITLE
@unocss/core必须使用0.49.8吗    

### ISSUE THREAD

**Issue by mwj610** [Dunqing/unocss-preset-theme#7]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/52907799/222902987-2b42cab7-a2d9-4178-838d-2354d0ddba45.png">

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/52907799/222902551-2c43f75e-34b5-43a7-a4f3-2854afd41b7b.png">

**Comment by HuangYaobin** [comment]
请问这个后来怎么解决的 我也报了同样的错误

**Comment by mwj610** [comment]
> 请问这个后来怎么解决的 我也报了同样的错误

我是把 node_modules 删了 重新install一下

**Comment by Dunqing** [comment]
这个问题就是自己装的 unocss 的版本和这个 preset 依赖的版本不一致导致的。重新 install，如果没效果可以删除lock文件重新下载，或者用 https://pnpm.io/package_json#pnpmoverrides 把 unocss 的版本固定。

**Comment by Dunqing** [comment]
我更新了下依赖，发了个新版本，下载最新的应该就没问题了。
