### ISSUE TITLE
type definition errors on presetTheme

### ISSUE THREAD

**Issue by MellKam** [Dunqing/unocss-preset-theme#8]
![image](https://user-images.githubusercontent.com/51422045/223807367-d4465431-f149-45fe-83b7-5773a360c507.png)

My code - 
```ts
import { defineConfig, presetUno } from 'unocss';
import presetTheme from 'unocss-preset-theme';
import type { Theme } from 'unocss/preset-uno';

export default defineConfig({
  theme: {
    colors: {
      primary: '#1677ff',
      'primary-border': '#1677ff',
      text: 'rgba(0, 0, 0, 0.88)',
      container: '#ffffff',
      border: '#d9d9d9',
    },
    spacing: {
      xss: '4px',
      xs: '8px',
      sm: '12px',
      base: '16px',
      lg: '24px',
      xl: '32px',
    },
  },
  presets: [
    presetUno(),
    presetTheme<Theme>({
      theme: {
        dark: {
          colors: {
            primary: '#1668dc',
            'primary-border': '#1668dc',
            border: '#424242',
            container: '#141414',
            text: 'rgba(255, 255, 255, 0.85)',
          },
        },
        compact: {
          spacing: {
            xss: '2px',
            xs: '4px',
            sm: '6px',
            base: '8px',
            lg: '12px',
            xl: '16px',
          },
        },
      },
    }),
  ],
});

```

Reproduction - https://codesandbox.io/p/sandbox/distracted-wilson-tydk5g?welcome=true

I saw you already have this issue, but for some reason it is not fixed. https://github.com/Dunqing/unocss-preset-theme/issues/4

**Comment by Dunqing** [comment]
Hi, Thank you for your feedback, you can install the latest version, and this issue will be fixed.

**Comment by MellKam** [comment]
Hi! I updated the version in codesandbox, but it still gives an error :(
https://codesandbox.io/p/sandbox/distracted-wilson-tydk5g?welcome=true

**Comment by Dunqing** [comment]
Can you forget to re-install dependencies? 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/29533304/224530697-f76bb18a-c2e0-4f5a-9e72-4f30b727f7da.png">

The type error disappear when I re-install dependencies 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/29533304/224530874-e56736c5-24c5-4173-85eb-a34d33faceb5.png">

**Comment by MellKam** [comment]
Yes, sorry. Now it is works👌
Thanks for fix
